version: '2'

volumes:
  mysql_data: {}
  sqewly_backups: {}

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    volumes:
      - mysql_data:/app:delegated
    ports:
      - "3306:3306"
  sqewly:
    command: ["/wait/wait-for-it.sh", "mysql:3306", "--", "/app/sqewly.py", "-c", "/app/sample.conf"]
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app:cached
    links:
      - mysql
